#!/bin/sh
#
# makesrcdist - make a source distribution of TTF.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating ttf-$version.tar.gz...
git archive --format tar --prefix=ttf-$version/ HEAD | gzip -v9 >ttf-$version.tar.gz
gpg --detach-sign ttf-$version.tar.gz
